### ISSUE TITLE
make task runs indefinitely with this output

### ISSUE THREAD

**Issue by ageoldpun** [botandrose/eboshi_api_shootout#53] opened 2015-10-07 20:11 UTC
haskell_scotty:
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: eboshi-api-0.1.0.0 (user goal)
next goal: base (dependency of eboshi-api-0.1.0.0)
rejecting: base-4.8.1.0/installed-075..., 4.8.1.0, 4.8.0.0, 4.7.0.2, 4.7.0.1,
4.7.0.0 (global constraint requires ==4.6.0.1)
rejecting: base-4.6.0.1 (global constraint requires installed instance)
rejecting: base-4.6.0.0, 4.5.1.0, 4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0,
4.2.0.2, 4.2.0.1, 4.2.0.0, 4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global
constraint requires ==4.6.0.1)
Dependency tree exhaustively searched.

**Comment by BartMassey** [comment] 2015-10-08 06:54
For some reason, my patch to the .cabal file to relax version constraints keeps getting reverted. I don't think I understand how you folks are using git.

**Comment by botandrose** [comment] 2015-10-08 08:36
That was almost certainly me. I spent some time today fighting with Travis and Haskell version constraints, trying to get `cabal sandbox` and `cabal exec` working for maximum reproducibility, but ultimately failed and removed them altogether. Afterwards, I rebased and squashed the umpteen "oops" commits and tried to clean up the entire `haskell_scotty` branch to tell a coherent story. All that rewriting history probably obscured the past. Sorry about that. I don't normally rewrite other people's commits.

If you know how to solve this problem, a PR would be very welcome. That said, I don't think that Paul particularly cares about the Scotty impl, so if it doesn't run on a stock `brew install cabal-install` Mac OSX setup, I don't think he'll lose any sleep. I'm probably gonna implement environment-variable blacklisting of impls for those who don't want to bother setting up a particular language, but still would like to run `make`.

**Comment by BartMassey** [comment] 2015-10-08 20:54
Part of the problem is that the `cabal.config` file is checked into Git. It probably shouldn't be, even were the sandbox turned on: the whole point of the `eboshi-api.cabal` file is to describe the versions that the code is supposed to work with, and there should be no need to get more specific. Even on the Travis setup, you will probably eventually want to test against multiple versions of libraries.

I'm still not quite understanding the development model. Should I PR or just commit?

Also, can we merge and delete the `haskell_scotty` remote branch as per my suggestion elsewhere? I would prefer to do local branching only for ease of development?

**Comment by botandrose** [comment] 2015-10-08 21:42
Regarding `cabal.config` being in the repo, I definitely want to avoid the classic "works-on-my-machine" issue, at least for the moment, so I want to make sure we're running the exact same software everywhere. This is in line with the other impl's dependency management strategies, as well. 
If this impl becomes successful (i.e. it succeeds the existing eboshi app in production), I think that would be an appropriate time to think about making it more flexible, with regards to dependencies.

So with that goal in mind, it seems to me that if the problem is the `base` version, the issue is that we need to lock down `ghc` version as well, since `base` is directly tied to that? If so, I'm guessing that Homebrew's default Haskell version is ever so slightly different from Ubuntu's default Haskell version, so we would need to address that somehow. Is this something we can mandate in the `.cabal`, or will we have to address the version dependency by messaging the user?

Regarding the development model: The workflow is to always work on a branch, periodically rebasing on master, until said branch is complete and ready to merge into master (preferably ff, but I'm flexible on that). When you think the branch is ready, start a PR for discussion and review, and after all interested parties are satisfied with the branch, the merge will occur. Prefer small incremental PRs to big bang changes.

Of course there can be exceptions to this, e.g. typos on the README, but generally speaking, committing to master is forbidden.

Regarding the `haskell_scotty` branch, its nearing the end of the PR lifecycle, so I think its nearly ready for merge, pending feedback from yourself, which it looks like you just provided. Will follow-up there.

**Comment by BartMassey** [comment] 2015-10-09 06:46
> Regarding cabal.config being in the repo, I definitely want to avoid the classic "works-on-my-machine" issue, at least for the moment, so I want to make sure we're running the exact same software everywhere. 

I don't think that locking down specific versions of libraries is realistic for Haskell right now. It's a language whose version numbers in constant flux, and the Hackage libraries we're depending on even more so. Worse, there's no agreed-upon maintenance strategy in any of the Linux distros, and it's worse on non-Linux platforms: Debian has packages that duplicate a lot of Hackage packages, for example. All trying to lock down versions will do is guarantee "works-only-on-your-machine" because no one else will be able to build it to try it out. I've spent about a total of 3 hours trying to get this code to build on two different boxes running the same Debian Jessie release.

You could go back to the sandbox. As you say, you're still going to have to deal with `ghc` version issues, since it's a total pain to sandbox the compiler. The sandbox is the only way to feasibly control all the versions across hosts, though.

One of the strengths of Haskell is that code from mature libraries that compiles is likely to run, and to continue to run as long as it continues to compile. Strong static-typed stateless functional interfaces really solve the problems you might be worried about pretty completely. The version numbers change frequently, but the backward compatibility basically never is harmed until major-number releases. This is the reasoning behind the constraints in my version of the `.cabal` file.

**Comment by botandrose** [comment] 2015-10-09 06:56
Hmm, coming from my world, this feels so very wrong! But if you think its not a dangerous strategy, then let's give it a go! The whole reason I'm learning Haskell is to break my brain in half with different approaches, after all.

**Closed** 2015-10-18 22:43 UTC
Labels: haskell_scotty
